### ISSUE TITLE
same methods different names/signatures

### ISSUE THREAD

**Issue by kamikaze** [micropython/micropython#2437] opened 2016-09-20 13:11 UTC
Is it possible to make consistent method names/signatures for same classes like I2C for different ports? Because now it is not easy to write portable code:

```
    if self.pyboard:
        res = self._i2c.mem_read(3, FRAM_SLAVE_ID >>1, device_addr <<1)
    else:
        res = self._i2c.readfrom_mem(FRAM_SLAVE_ID >>1, device_addr <<1, 3)
```

**Comment by deshipu** [comment] 2016-09-20 13:56
The work on this is continuing. The idea is that if you import stuff from `pyb`, it has the old API (so as to not break people's programs), and if you import it from `machine`, it will have the new API.

**Comment by dpgeorge** [comment] 2016-09-27 06:39
This is kind of a duplicate of #2449.  To write portable code please use the machine module and the methods it defines for the peripherals.  pyboard does have machine.I2C but it's software only at the moment.

**Comment by pfalcon** [comment] 2017-05-14 20:38
Hopefully above comments answer it.

**Closed by pfalcon** 2017-05-14 20:38 UTC
Labels: stmhal

**Comment by dpgeorge** [comment] 2017-05-14 22:48
stmhal/pyboard's machine.I2C class is now fully function, uses HW acceleration and it's recommended to use it as a complete replacement for pyb.I2C.
