### ISSUE TITLE
ESP32D0WDQ6 - Chip revision is higher than the one configured in menuconfig. 

### ISSUE THREAD

**Issue by ds2k5** [micropython/micropython#5397] opened 2019-12-08 11:56 UTC
Hello,
I flashed the v1.11 on my ESP32D0WDQ6.

File: esp32-idf3-20191208-v1.11-624-g210d05328.bin

If reset the board I can see this:

**W (210) cpu_start: Chip revision is higher than the one configured in menuconfig. Suggest to upgrade it.**

>>> ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:4844
load:0x40078000,len:9656
load:0x40080400,len:6216
entry 0x400806f0
I (464) cpu_start: Pro cpu up.
I (464) cpu_start: Application information:
I (464) cpu_start: Compile time:     Dec  8 2019 00:37:55
I (467) cpu_start: ELF file SHA256:  0000000000000000...
I (473) cpu_start: ESP-IDF:          v3.3
I (478) cpu_start: Starting app cpu, entry point is 0x400832d0
I (0) cpu_start: App cpu up.
I (488) heap_init: Initializing. RAM available for dynamic allocation:
I (495) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (501) heap_init: At 3FFBA458 len 00025BA8 (150 KiB): DRAM
I (508) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (514) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (520) heap_init: At 40092A3C len 0000D5C4 (53 KiB): IRAM
I (527) cpu_start: Pro cpu start user code
I (209) cpu_start: Chip Revision: 1
**W (210) cpu_start: Chip revision is higher than the one configured in menuconfig. Suggest to upgrade it.**
I (213) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
MicroPython v1.11-624-g210d05328 on 2019-12-08; ESP32 module with ESP32
Type "help()" for more information.
>>> 

Board: http://www.lilygo.cn/claprod_view.aspx?TypeId=21&Id=1128&FId=t28:21:28

Can you build a version that includes the Chip revision on my board too ?

Thanks

**Comment by dpgeorge** [comment] 2019-12-09 02:17
Closing as a duplicate of #5128

**Closed by dpgeorge** 2019-12-09 02:17 UTC
Labels: port-esp32
