### ISSUE TITLE
docs: Broken Link

### ISSUE THREAD

**Issue by mwerezak** [micropython/micropython#8818] opened 2022-06-25 15:23 UTC
* Describe what was missing from the documentation and/or what was incorrect/incomplete.

In file:
https://github.com/micropython/micropython/blob/master/docs/reference/packages.rst#creating-distribution-packages

> The sdist_upip.py module as referenced above can be found in [micropython-lib](https://docs.micropython.org/en/latest/reference/glossary.html#term-micropython-lib): https://github.com/micropython/micropython-lib/blob/master/sdist_upip.py

The link is broken

* If possible, please link to the relevant page on https://docs.micropython.org/

https://docs.micropython.org/en/latest/reference/packages.html#creating-distribution-packages

**Comment by andypiper** [comment] 2022-06-30 12:54
Duplicate of #7908

**Comment by jonnor** [comment] 2023-07-30 02:36
Duplicate. Proposing to close

**Closed** 2023-07-31 07:12 UTC
Labels: docs
