### ISSUE TITLE
Set hostname on cyw43-based boards

### ISSUE THREAD

**Issue by scruss** [micropython/micropython#8910] opened 2022-07-14 14:47 UTC
Please consider adding a method to set `WLAN.config(hostname="...")` on boards with cyw43 network drivers. This is useful for people with multiple Raspberry Pi Pico W and pyboard D-series as a way to tell them apart on a LAN. I realize, however, that hostname configuration is one of the optional parts of the [WLAN](http://docs.micropython.org/en/latest/library/network.WLAN.html) class, so this is icing rather than cake.

Ports affected: stm32, rp2, and any others that might use cyw43.

Confirmation of issue: [Re: Setting hostname on Pico W](https://forum.micropython.org/viewtopic.php?p=69035#p69035)

Implementing this safely is beyond my limited means, both technically and as a (very minor) sponsor.

**Comment by dpgeorge** [comment] 2022-07-15 00:18
Yes, definitely a good thing to implement.

Closing as a duplicate of #8906.

**Closed by dpgeorge** 2022-07-15 00:18 UTC
Labels: enhancement
