### ISSUE TITLE
Can upy be debugged with Visual Studio Code like CPython?

### ISSUE THREAD

**Issue by fei2020** [micropython/micropython#4796] opened 2019-05-18 16:07 UTC
Can upy be debugged with Visual Studio Code(vscode) like CPython(with a vscode's Python extension by M$ )?
Visual Studio is a light excellent platform-independent code editor like Sublime and Atom. It is increasingly accepted by the GNU world.

**Comment by stinos** [comment] 2019-05-18 16:19
Duplicate of #3009 and others, in short: no.

**Closed** 2024-09-19 15:41 UTC
