### ISSUE TITLE
esp8266 SPI write() Doesn't Finish Before CS Goes High

### ISSUE THREAD

**Issue by semireg** [micropython/micropython#3487] opened 2017-12-13 14:08 UTC
The following code generates the following image screenshot from a protocol analyzer.

```
    data = bytearray([0x8A, 0x1A])
    pin_cs.value(False)
    spi.write(data)
    pin_cs.value(True)
```

![2017-12-12 at 10 56 am](https://user-images.githubusercontent.com/1819762/33942582-07e04bcc-dfdc-11e7-96f1-269d122e21ba.jpg)

Changing to write_readinto seems to fix the issue:

```
    data = bytearray([0x8A, 0x1A])
    rd = bytearray(2)
    pin_cs.value(False)
    spi.write_readinto(data, rd)
    pin_cs.value(True)
```

Is this the expected behavior of write()?

```
esptool.py v2.2
esp8266-20171101-v1.9.3.bin
Adafruit Feather HUZZAH ESP8266
```

**Comment by dpgeorge** [comment] 2017-12-13 23:46
Thanks for the report.  The issue is that the SPI.write() function returns with data still pending to be clocked out (whereas SPI.write_readinto() must wait for the last byte to come in before returning).  It should be fixed now by badaf3ecfe5d0c8158debf4bd0cb1458016c77f4

**Closed by dpgeorge** 2017-12-13 23:46 UTC
