### ISSUE TITLE
pyboard: current firmware breaks rshell

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2034] opened 2016-05-06 07:32 UTC
rshell connects to the board, but any attempt to copy a file to /sd causes a hang. I've reverted to 29th April (3f3ccef8292414d99d4ebd19eddebc6db3124bc4) as a workround, so the fail has occurred since then.

**Comment by dpgeorge** [comment] 2016-05-06 09:40
Confirmed.  Looks like the bug comes in with the L4 modifications to the DMA sub-system: e64032d6fdeb079de2ace20b64899d1ceb6754f1

**Comment by dpgeorge** [comment] 2016-05-06 09:54
Should be fixed by 88153dc56a03938473fca8c0de46535f8ae3109b.

**Closed by dpgeorge** 2016-05-06 09:54 UTC
