### ISSUE TITLE
viper: odd behaviour assigning to bytearray

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1842] opened 2016-02-14 09:13 UTC
bar() works as expected but foo() seems to have an issue assigning ord('a')
```python
from uctypes import addressof
@micropython.viper       
def foo(data):
    p = ptr8(addressof(data))
    p[0] = ord('a')
    print(data, len(data), ord('a'))

@micropython.viper       
def bar(data):
    p = ptr8(addressof(data))
    p[0] = 97
    print(data, len(data))
```
Outcome:
```
>>> foo(bytearray('zxy'))
bytearray(b'\xc3xy') 3 97
>>> bar(bytearray('zxy'))
bytearray(b'axy') 3
```

**Comment by dpgeorge** [comment] 2016-02-15 09:43
The issue is that ord('a') is an object (not a native viper integer, needs a cast for that) and it's silently allowing the store of an object to a ptr8 destination.  Fixed in 9598f36a84e19045e2978ab902e2367dc2fa12d4 by adding a type check.

**Closed by dpgeorge** 2016-02-15 09:43 UTC
