### ISSUE TITLE
docs: network hostname on different ports

### ISSUE THREAD

**Issue by massimosala** [micropython/micropython#11545] opened 2023-05-18 18:35 UTC
It seems on esp8266 this function is useless:

> network.hostname()

Please see https://github.com/micropython/micropython/issues/11450

Does anybody confirm this?
If it is unsupported, I think

1. It has to be documented, ASAP.
2. It would be nice to fix: remove the function from the ports where it doesn't do anything or leave it but reporting that it doesn't work.

On how to report to the caller of the function, should a NotImplementedError be raised?

**Comment by jimmo** [comment] 2023-05-19 14:09
Closing as duplicate of https://github.com/micropython/micropython/issues/11450

**Closed by jimmo** 2023-05-19 14:09 UTC
