### ISSUE TITLE
Pyboard: Cannot use safe mode and factory reset

### ISSUE THREAD

**Issue by IlysvlVEizbr** [micropython/micropython#8528] opened 2022-04-13 04:00 UTC
@dpgeorge 
Firmwares with this problem:
pybv11-thread-20210902-v1.17.dfu and any newer
( including latest pybv11-thread-20220413-unstable-v1.18-330-gd242a9b7f.dfu)

This problem **only** appears in firmwares with **threading feature**.

Reproducible steps:
1. Hold down the USR switch.
2. While still holding down USR, press and release the RST switch.
3. Let go of the USR switch.

Specific phenomenon:
1. The green LED always keeps on.
2. PC cannot recognize pyboard.
3. No py script is run.

Also see #7935 and #7816

**Comment by jimmo** [comment] 2022-08-25 02:10
Duplicate of #7816

**Closed by jimmo** 2022-08-25 02:10 UTC
