### ISSUE TITLE
STM32L476 dfu upgrade bug

### ISSUE THREAD

**Issue by shaoziyang** [micropython/micropython#2637] opened 2016-11-15 15:09 UTC
When I upgrade firmware for STM32L476 using dfu file ,it is not run after download.

But when I upgrade firmware using hex file, it works.

**Comment by dhylands** [comment] 2016-11-15 20:25
This appears to be an issue with dfu-util and not micropython. It also appears to be on their radar, but no specific fix has been posted yet: https://sourceforge.net/p/dfu-util/tickets/27/

I was able to reproduce the problem (i.e. if I flash my STM32L476 using dfu-util then it doesn't boot properly). However, if I flash the exact same image using pydfu.py then everything seems to be working fine.

**Comment by dpgeorge** [comment] 2016-11-16 00:19
Yes, this is an issue for dfu-util.  I would suggest using tools/pydfu.py from this repository, which is the default if you do "make deploy" in stmhal directory.  You can also use an st-link device.

**Closed by dpgeorge** 2016-11-16 00:19 UTC
