### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by kahveciderin** [micropython/micropython#6624] opened 2020-11-15 12:47 UTC
Error while compiling for SAMD51
```tusb_port.c:72:62: error: macro "TUD_CONFIG_DESCRIPTOR" requires 6 arguments, but only 5 given
   72 |         TUSB_DESC_CONFIG_ATT_REMOTE_WAKEUP, USBD_MAX_POWER_MA),
      |                                                              ^
In file included from ../../lib/tinyusb/src/tusb.h:65,
                 from tusb_port.c:28:
../../lib/tinyusb/src/device/usbd.h:180: note: macro "TUD_CONFIG_DESCRIPTOR" defined here
  180 | #define TUD_CONFIG_DESCRIPTOR(config_num, _itfcount, _stridx, _total_len, _attribute, _power_ma) \
      | 
tusb_port.c:71:5: error: 'TUD_CONFIG_DESCRIPTOR' undeclared here (not in a function)
   71 |     TUD_CONFIG_DESCRIPTOR(USBD_ITF_MAX, USBD_STR_0, USBD_DESC_LEN,
      |     ^~~~~~~~~~~~~~~~~~~~~
tusb_port.c:94:17: error: conflicting types for 'tud_descriptor_string_cb'
   94 | const uint16_t *tud_descriptor_string_cb(uint8_t index) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../lib/tinyusb/src/tusb.h:65,
                 from tusb_port.c:28:
../../lib/tinyusb/src/device/usbd.h:108:17: note: previous declaration of 'tud_descriptor_string_cb' was here
  108 | uint16_t const* tud_descriptor_string_cb(uint8_t index, uint16_t langid);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [../../py/mkrules.mk:77: build-ADAFRUIT_ITSYBITSY_M4_EXPRESS/tusb_port.o] Error 1
```

**Comment by dpgeorge** [comment] 2021-04-14 06:18
I think the issue is a mismatch in the tinyusb version.  `git submodule update --init lib/tinyusb` should fix it.  Also see `tools/ci.sh` for how CI builds the samd port, that should show how to get it working.

I'll close this issue.  Feel free to reopen if there are still problems building.

**Closed by dpgeorge** 2021-04-14 06:18 UTC
Labels: port-samd
