### ISSUE TITLE
Add support for MessagePack

### ISSUE THREAD

**Issue by scls19fr** [micropython/micropython#4241] opened 2018-10-15 10:01 UTC
Hello,

Related #4200 
Supporting an other binary serializer/deserializer such as MessagePack could be a nice feature also.

I noticed
https://github.com/msgpack/msgpack-python
and https://github.com/vsergeev/u-msgpack-python

but I'm not sure if it's currently available for micropython.

Is there unit tests framework such as pytest on micropython because u-msgpack-python uses it? ... 

Not sure pytest is available on micropython according https://github.com/construct/construct/issues/224#issuecomment-269878165

Kind regards

**Comment by EcmaXp** [comment] 2018-10-17 03:16
https://github.com/EcmaXp/OpenPie/blob/master/oprom/msgpack.c

**Comment by EcmaXp** [comment] 2018-10-17 03:18
mpack library is good for embedding to micropython.
https://github.com/ludocode/mpack

**Comment by kingsjl** [comment] 2019-06-05 12:14
> mpack library is good for embedding to micropython.
> https://github.com/ludocode/mpack

how to use?

**Comment by stinos** [comment] 2019-06-05 12:26
Don't know about mpack, but the 'official' MessagePack Python implementation (i.e. what you get when installing via pip or conda, all .py files from https://github.com/msgpack/msgpack-python/tree/master/msgpack) almost works out of the box for basic usecases. The only problem is it uses multiple inheritance for it's exceptions, which MicroPython doesn't support, but is failry easy to fix: modify 2 lines and make `FormatError` and `StackError` derive only from `UnpackException`.

**Comment by smurfix** [comment] 2021-06-02 15:03
Well, the "official" msgpack implementation is inefficient as heck. Encoding a single three-element dict takes ~1k memory. Owch.

I'm working on simplifying and rewriting it so that it uses (small) buffers, instead of copying data all over the place. Will be part of my microfuse project (https://github.om/M-o-a-T/microfuse) shortly.

**Comment by stinos** [comment] 2021-06-02 15:15
> Well, the "official" msgpack implementation is inefficient as heck. Encoding a single three-element dict takes ~1k memory. Owch.

Which implementation, one of the Python implementations? Or the C one?

**Comment by peterhinch** [comment] 2021-06-02 15:42
> my microfuse project (https://github.com/M-o-a-T/microfuse)

404

**Comment by smurfix** [comment] 2021-06-02 16:25
> > Well, the "official" msgpack implementation is inefficient as heck. Encoding a single three-element dict takes ~1k memory. Owch.
> 
> Which implementation, one of the Python implementations? Or the C one?

Python. I haven't looked at details of the C implementation because I have no free week to write a MicroPython interface for it. Mostly-fixing the Python code is childs play by comparison.

> > my microfuse project (https://github.com/M-o-a-T/microfuse)
> 
> 404

The original mail had a typo (github.om). Since fixed, please try again.

**Comment by stinos** [comment] 2021-06-02 17:03
> Python. I haven't looked at details of the C implementation because I have no free week to write a MicroPython interface for it. Mostly-fixing the Python code is childs play by comparison.

Assuming you mean the one linked above, did you also check https://github.com/vsergeev/u-msgpack-python ?

**Comment by smurfix** [comment] 2021-06-02 18:10
> Assuming you mean the one linked above, did you also check https://github.com/vsergeev/u-msgpack-python ?

I just looked at it. Same inefficiency problems. Worse, the author doesn't even seem to know that you can write
```
if py2:
    def proc():
        …  # py2 version
else:
    def proc():
        …  # py3 version
```
. Even worse it doesn't support unpacking a stream of messages, which is a required exercise with `msgpack` because the protocol is self-delimiting.

One use case is OTA updates. If you can't even send a 4k bytestring to or from the device without running into intermittent errors, even though `gc` says you have >30k of free memory, you have a problem. Thus you need to return large byte objects as memoryview into the decoder's input buffer, which must itself be a static bytearray. 

On the plus side my rewrite is almost done and all I need to do is test (and document …) it.

On the minus side there's a memory error in MicroPython somewhere in the bytearray slicing/assignment code. I haven't been able to reproduce it yet, but I frequently get this:
```
assertion "ATB_GET_KIND(block) == AT_HEAD" failed: file "/home/smurf/src/micropython/py/gc.c", line 591, function: gc_free
```

**Comment by stinos** [comment] 2021-06-02 18:31
> The original mail had a typo (github.om). Since fixed, please try again.

Still 404

> Worse, the author doesn't even seem to know that you can write `if py2`

What is `py2`?

> On the minus side there's a memory error in MicroPython somewhere in the bytearray slicing/assignment code.

Is this the same as https://github.com/micropython/micropython/issues/7261 and if so did you try with a version which includes the fix for that? Otherwise please create an issue with code to reproduce this.

**Comment by smurfix** [comment] 2021-06-02 18:57
> > The original mail had a typo (github.om). Since fixed, please try again.
> 
> Still 404
> 
I have no idea which link you're trying, but https://github.com/M-o-a-T/microfuse works perfectly for me.

> > Worse, the author doesn't even seem to know that you can write `if py2`
> 
> What is `py2`?
> 
Some check whether you're running on python2 or python3. Sorry, I thought that'd be obviousl

> > On the minus side there's a memory error in MicroPython somewhere in the bytearray slicing/assignment code.
> 
> Is this the same as #7261 and if so did you try with a version which includes the fix for that? Otherwise please create an issue with code to reproduce this.

Unfortunately not. I will as soon as I can actually reproduce the thing.

**Comment by stinos** [comment] 2021-06-03 07:26
> but https://github.com/M-o-a-T/microfuse works perfectly for me

Test in a private browser window or when not logged in into github, it has probably non-public accessibility.

> Some check whether you're running on python2 or python3. Sorry, I thought that'd be obvious.

That part is obvious, what is not obvious is where you get it from, and/or what you really mean with your rant :) But it's off-topic anyway.

**Comment by dpgeorge** [comment] 2021-08-04 05:44
See this new library by @peterhinch : https://github.com/peterhinch/micropython-msgpack

**Closed** 2024-07-04 11:17 UTC
Labels: enhancement
