### ISSUE TITLE
Feature request: match case statement

### ISSUE THREAD

**Issue by fzhwenzhou** [micropython/micropython#8769] opened 2022-06-17 06:07 UTC
I know that some features in Python 3.10 have been added into MicroPython, but this feature is not. This is especially useful when output of SPI contains abundant circumstances. In my opinion, it is simpier to use this rather than a series of "if...elif...elif...", and it is not hard to implement (just a minor modification of "if" code).
I would appreciate it if someone could make it a reality.

**Comment by jimmo** [comment] 2022-06-17 06:15
Duplicate of https://github.com/micropython/micropython/issues/7847

It's a great feature, but sadly it is definitely not a "minor modification of if code".

**Closed by jimmo** 2022-06-17 06:15 UTC
Labels: enhancement
