### ISSUE TITLE
builtin modules don't show up in sys.modules when imported

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1759] opened 2015-12-31 22:41 UTC
I noticed that when you import builtin modules, like sys, time, os, that they don't show up in sys.modules. Is this intentional?

In CPython, builtin modules show up like:

```
'_io': <module 'io' (built-in)>
```

**Comment by pfalcon** [comment] 2016-01-01 10:38
No, it's natural way the code works. It would require intentional intervening to do otherwise.

Happy New Year!

**Comment by pfalcon** [comment] 2016-01-10 22:13
As this not a bug, I suggest closing this.

**Comment by dpgeorge** [comment] 2016-01-11 00:45
The behaviour is a diversion from CPython.  But since there is no argument for having it othewise closing is fine with me.

**Closed** 2024-08-28 05:13 UTC
Labels: wontfix
