### ISSUE TITLE
Second import of module that is too large should fail too

### ISSUE THREAD

**Issue by tannewt** [micropython/micropython#2450] opened 2016-09-23 01:19 UTC
I'm trying to load a module whose parse tree is too large. The first `import` fails with a `MemoryExceeded` exception. However, if I import it a second time it "succeeds" but the object doesn't have all of the correct properties (aka it didn't actually load). Looks like some cache isn't being purged after the load failure.

```
>>> import os
>>> os.listdir()
['main.py', 'README.txt', 'boot.py', 'ht16k33_matrix.py', 'test.py', 'is31fl3731.py']
>>> import is31fl3731
GC: total: 15936, used: 15392, free: 544
 No. of 1-blocks: 10, 2-blocks: 21, max blk sz: 87, max free sz: 20
GC: total: 15936, used: 15744, free: 192
 No. of 1-blocks: 24, 2-blocks: 33, max blk sz: 87, max free sz: 5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 176 bytes
>>> dir(is31fl3731)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'is31fl3731' is not defined
>>> import is31fl3731
>>> dir(is31fl3731)
['__name__', '__file__']
```

**Comment by dpgeorge** [comment] 2016-09-23 01:34
Duplicate of #967.

**Closed by dpgeorge** 2016-09-23 01:34 UTC
