### ISSUE TITLE
Trying to #include "esp_wpa2.h", Failing

### ISSUE THREAD

**Issue by MATTYGILO** [micropython/micropython#8841] opened 2022-06-30 10:00 UTC
I'm using an esp32 and creating a custom micropython function, however the project fails to build when trying to #include "esp_wpa2.h". From esp-idf.

How do I #include a function from esp idf.

What do I need to add to cmake and make for this work?

**Comment by jimmo** [comment] 2022-06-30 10:11
Please provide more information -- see the [new issue template](https://github.com/micropython/micropython/issues/new?assignees=&labels=bug&template=bug_report.md&title=) as a guide. Did it work before you added a function, which commands did you execute, which versions of everything, etc.

My guess is you have the wrong IDF version or something wrong with the IDF environment. See ports/esp32/README.md

**Comment by MATTYGILO** [comment] 2022-06-30 12:03
@jimmo I get this error
`fatal error: esp_wpa2.h: No such file or directory`

**Comment by jimmo** [comment] 2022-06-30 12:10
Please see my questions above.

**Comment by dpgeorge** [comment] 2022-07-08 12:18
I'll close this issue because it doesn't have enough information on how to reproduce the problem.

**Closed by dpgeorge** 2022-07-08 12:18 UTC
Labels: bug
