### ISSUE TITLE
Wifi not working with micropython 1.19.1 esp32 S3 generic spiram

### ISSUE THREAD

**Issue by remibert** [micropython/micropython#8779] opened 2022-06-18 15:06 UTC
It seems to freeze when the wifi station starts connecting (not sure if it's wifi, it's just the last trace of activity I have on my app). Micropython 1.18 also has the same problem.

I recompiled micropython 1.19.1 with esp-idf 4.4.1, it fixes the problem and the wifi connection works.

Esp-idf 4.4.1 works perfectly fine on esp32cam, esp32 generic, esp32 spiram and also esp32 s3 spiram, I haven't tested on esp8266.

**Comment by dpgeorge** [comment] 2022-06-18 15:15
Duplicate of #8635.

**Closed by dpgeorge** 2022-06-18 15:15 UTC
Labels: bug, port-esp32
