### ISSUE TITLE
Inheritance in C - add derived methods to a derived class.

### ISSUE THREAD

**Issue by israelg99** [micropython/micropython#1926] opened 2016-03-23 23:15 UTC
My understanding is that to apply inheritance in MicroPython, you do something like this:
```
const mp_rom_obj_tuple_t mp_bar_type_base_tuple = {{&mp_type_tuple}, 1, {MP_ROM_PTR(&mp_bar_type)}};

mp_obj_type_t mp_type_foo = {
		{ &mp_type_type },
		.name = MP_QSTR_Foo,
		.print = mp_foo_print,
		.make_new = mp_foo_make_new,
		.locals_dict = (mp_obj_t) &mp_foo_locals_dict,
		.bases_tuple = (mp_obj_tuple_t*)(mp_rom_obj_tuple_t*)&mp_bar_type_base_tuple, // inheritance(?).
};
```
Here `Foo` is a subclass of `Bar`, however `Foo` cannot use any of Bar's methods because:
`AttributeError: 'Foo' object has no attribute 'anyBarFunc'`

Therefore, I decided to set Foo's local dict to Bar's:
`.locals_dict = (mp_obj_t) &mp_bar_locals_dict,`

Foo can use Bar's methods now, but how does Foo come about to having his own, derived methods - `mp_foo_locals_dict`?

For overwriting, I currently just check types, for example in the `make_new()` I just check whether `type_in` is `Bar` or `Foo`, not sure if that's the best way, so let me know.

I was referencing [objexcept.c](https://github.com/micropython/micropython/blob/master/py/objexcept.c#L189) and [objdict.c](https://github.com/micropython/micropython/blob/master/py/objdict.c#L585).

Any ideas?

**Comment by pfalcon** [comment] 2016-03-24 09:54
Duplicate of https://github.com/micropython/micropython/issues/1159

**Closed by pfalcon** 2016-03-24 09:54 UTC
