### ISSUE TITLE
int.to_bytes and int.from_bytes implementations incomplete

### ISSUE THREAD

**Issue by khoulihan** [micropython/micropython#682] opened 2014-06-11 16:28 UTC
These methods have the following comments in them:

// TODO: Support long ints
// TODO: Support byteorder param
// TODO: Support signed param

I encountered this when trying to convert an int to big-endian bytes, but to_bytes returned little-endian bytes instead. from_bytes also apparently only supports little-endian bytes.

**Comment by nickovs** [comment] 2017-01-05 16:21
I just ran into another part of this issue: the lack of support for ints longer than the machine word (mp_uint_t) size.
```
>>> b = b"\xff" * 16
>>> b
b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
>>> hex(int.from_bytes(b, "big"))
'0xffffffff'
>>> 
```
This makes it tedious to do security protocols that use larger numbers.

**Comment by peterhinch** [comment] 2017-01-06 07:32
At risk of stating the obvious, this is easily done in Python; the essence of MicroPython is keeping the firmware "micro".
```python
def from_bytes_big(b):
    n = 0
    for x in b:
        n <<= 8
        n |= x
    return n
```
```python
>>> hex(from_bytes_big((b"\xff" * 16) + b"\xaa"))
'0xffffffffffffffffffffffffffffffffaa'
```

**Comment by pfalcon** [comment] 2017-01-06 08:07
The problem here is that it silently gives incorrect result. We definitely need to fix it, and I'm actually set to make it work, not just throw NotImplementedError. I have code in works. (Because otherwise we have pretty gappy implementation, e.g. .to_bytes() works with long ints, and .from_bytes() suddenly doesn't. That's also why I'm conservative about adding anything new to the core - we need to spend quite a bunch of bytes to make what we already have work right.)

**Comment by nickovs** [comment] 2017-01-06 16:53
@peterhinch 

> At risk of stating the obvious, this is easily done in Python

As @pfalcon says, the issue is that this silently behaves differently to the Python 3 specification. Since `from_bytes()` is a class method of a rather fundamental built-in type, overriding 'int' to add your Python patch to fix this is probably not a good idea. This means existing code actually needs to be ported and the silent error means people might not know that they need to do this.

@pfalcon  I'm glad to hear that this is already on the cards. Are you also already working on fixing the three-paramater `pow(x,y,z)` function to not require O(log(x).y) memory? I'm happy to fix this if it's not already in progress but it looks like most of the code is already in there and just not switched on. If someone else is already half way through this then I will let them get on with it.

**Comment by pfalcon** [comment] 2017-01-07 08:49
@nickovs

> This means existing code actually needs to be ported

Fairly speaking, that's the recommended way to deal with existing CPython-written code (.from_bytes() will be fixed, but I'm afraid there will be many more missing features which uPy doesn't, and can't realistically, implement).

> Are you also already working on fixing the three-paramater pow(x,y,z) function to not require O(log(x).y) memory?

As a quick answer, I don't. However, so happens that I hit a usecase for it lately either (writing CPython-intended code): https://github.com/pfalcon/yaota8266/blob/master/ota-client/rsa_sign.py#L43 . I try to write any Python code lately to be compatible with uPy, and noted that 3-arg pow() would be a problem. But somehow, a snapshot I had in my mind is that uPy didn't support 3 args to pow(), only 2, but perhaps I'm mixing it up now, and the issue was that for RSA-level numbers, the operation was just too slow. Anyway, you'd need to talk with @dpgeorge about optimizing that case (he's the author of mpz library), but I'm afraid, that really would be a case to invoke a rule-of-thumb which @peterhinch talks about, and even if such optimization is done, it would be disabled by default.

P.S. I submitted a proposal for a talk on MicroPython and other scripting languages for OpenIoT Summit and now (im)patiently waiting for a reply. Keeping fingers crossed it's accepted, we can talk there in detail about uPy's approach/evolution (assuming you will be there, as collocated with ELC).

**Comment by dpgeorge** [comment] 2017-01-08 07:56
> Are you also already working on fixing the three-paramater pow(x,y,z) function to not require O(log(x).y) memory? I'm happy to fix this if it's not already in progress but it looks like most of the code is already in there and just not switched on.

See ff1a96ce2cd95c42beca5209b353f83da773522d for the commit that added the mpz-optimised version of pow3.  IIRC, that version is no faster than doing x**y followed by %z, so that's why I never plumbed it into the rest of the code.  But of course it is better in terms of memory use, as noted in that git comment (although I don't know if it's optimal).  If there's demand/good reason to enabled this optimised version then it can be done via a compile-time option.  There're already optimisations for mpz bit-wise ops (see MICROPY_OPT_MPZ_BITWISE) and arguably a pow3 memory-optimisation is more important than bit-wise speed opts.

**Comment by nickovs** [comment] 2017-01-08 15:41
Assuming x and z are about the same size (which is the case for most crypto operations) the time complexity of the old version is approximately O(log(z)^2.y^2.log(y)) and the complexity of the optimised version is O(log(z)^2.log(y)), a factor of y^2 faster. Note that that is the **value** of y, not the **size** of y, so for something like the a typical RSA public key operation (e=0x10001) not only would the old version need more than 4GB of RAM but it would be about 2^32 times slower. RSA private key operations would need more than 2^1024 bytes of RAM and be 2^1024 times slower! For very small values of y the difference may be masked by other costs.

The utility of pow(x,y,z) for MicroPython is in implementing lightweight protocols for securing IoT connections. For transport security users should be using TLS but there are things like authentication protocols that would benefit from this working. For the typical values of y in these protocols the existing code simply won't work. As with the from_bytes() method, the optimised version could of course be written out longhand in Python. That said, since the functionality is defined in the Python3 spec and the fix exists and looks like it should only need a few dozen bytes of code on a Thumb, I would argue for it being included by default with a compile-time switch for people who's ROM space if extremely constrained.

**Comment by rhubarbdog** [comment] 2018-12-27 12:41
The OP stated that signed keyword was to be implemented. Has this been done?
As I have the error
```
bytes_ = int(-100).to_bytes(4, 'little', True)

print(str(bytes_))
print('signed', int.from_bytes(bytes_, 'little', True))
print('unsigned', int.from_bytes(bytes_, 'little'))
```
outputs the following
```
b'\x9c\xff\xff\xff'
signed 4294967196
unsigned 4294967196
```

**Comment by nickovs** [comment] 2018-12-27 15:09
A quick check of the [current code](https://github.com/micropython/micropython/blob/fa50047bbc25a2db53ef2c38b7735a4dedb23b21/py/objint.c#L419) suggests that the `to_bytes()` method still does not implement the `signed` flag. The same goes for the [current implementation](https://github.com/micropython/micropython/blob/fa50047bbc25a2db53ef2c38b7735a4dedb23b21/py/objint.c#L387) of the `from_bytes()` method. @pfalcon said way back that he has code for doing this so perhaps he might comment. It shouldn't be hard to fix this.

**Comment by thestumbler** [comment] 2019-08-12 11:30
I ran into this issue (signed integer not working) using `int.from_bytes()` this evening.  I made a work-around in my user code.  If it helps, I'm using this version:
```
MicroPython v1.11-187-g00e7fe8ab-dirty 
on 2019-08-08; NUCLEO-F429ZI with STM32F429
```

**Comment by projectgus** [comment] 2024-08-28 04:46
I think from the original report the `signed` argument (and the difference in default behaviour re: signedness) is the only piece still missing.

There's a newer issue at #15399 which is technically a duplicate of this issue but it captures the current situation better, so closing in favour of it.

**Closed by projectgus** 2024-08-28 04:46 UTC
Labels: notimpl, prio-low
