### ISSUE TITLE
struct.unpack_from() return a wrong result, when the third parameter was none zero

### ISSUE THREAD

**Issue by HotIce0** [micropython/micropython#4876] opened 2019-06-26 22:23 UTC
### File path
in  /py/modstruct.c this file.

### Detailed
STATIC mp_obj_t struct_unpack_from(size_t n_args, const mp_obj_t *args).
this function has something wrong. because

```python
>>> struct.unpack_from("hhhh", b'S\xcb\xff\x05\x00\xf9\xfb\r)\xa1UV', 1)
(1535, -1792, 3579, -24279) # this is output from micropython on esp32 struct module. this result was wrong.
```

```python
print(struct.unpack_from("hhhh", b'S\xcb\xff\x05\x00\xf9\xfb\r)\xa1UV', 1))
(-53, 5, -1031, 10509) # this output from python3.7, that's right
```

### ....
I think the error should be here. marked with //*****

```C
STATIC mp_obj_t struct_unpack_from(size_t n_args, const mp_obj_t *args) {
    // unpack requires that the buffer be exactly the right size.
    // unpack_from requires that the buffer be "big enough".
    // Since we implement unpack and unpack_from using the same function
    // we relax the "exact" requirement, and only implement "big enough".
    const char *fmt = mp_obj_str_get_str(args[0]);
    size_t total_sz;
    size_t num_items = calc_size_items(fmt, &total_sz);
    char fmt_type = get_fmt_type(&fmt);
    mp_obj_tuple_t *res = MP_OBJ_TO_PTR(mp_obj_new_tuple(num_items, NULL));
    mp_buffer_info_t bufinfo;
    mp_get_buffer_raise(args[1], &bufinfo, MP_BUFFER_READ);
    byte *p = bufinfo.buf;
    byte *end_p = &p[bufinfo.len];
    mp_int_t offset = 0;

    if (n_args > 2) {
        // offset arg provided
        offset = mp_obj_get_int(args[2]);
        if (offset < 0) {
            // negative offsets are relative to the end of the buffer
            offset = bufinfo.len + offset;
            if (offset < 0) {
                mp_raise_ValueError("buffer too small");
            }
        }
        p += offset;
    }

    // Check that the input buffer is big enough to unpack all the values
    if (p + total_sz > end_p) {
        mp_raise_ValueError("buffer too small");
    }

    for (size_t i = 0; i < num_items;) {
        mp_uint_t cnt = 1;
        if (unichar_isdigit(*fmt)) {
            cnt = get_fmt_num(&fmt);
        }
        mp_obj_t item;
        if (*fmt == 's') {
            item = mp_obj_new_bytes(p, cnt);
            p += cnt;
            res->items[i++] = item;
        } else {
            while (cnt--) {   // *******first time in this loop, cnt is 1, cnt-- then cnt equals 0. so nothing was do. 
                item = mp_binary_get_val(fmt_type, *fmt, &p);
                res->items[i++] = item;
            }
        }
        fmt++;
    }
    return MP_OBJ_FROM_PTR(res);
}
```

**Comment by dpgeorge** [comment] 2019-06-27 00:32
This is a duplicate of #3314

**Closed by dpgeorge** 2019-06-27 00:32 UTC
