### ISSUE TITLE
 week cannot be set correctly on ESP 32

### ISSUE THREAD

**Issue by kekemuyu** [micropython/micropython#4547] opened 2019-02-24 13:35 UTC
I try to init the datetime with `rtc.datetime((2019,2,24,0,19,46,0,0))` or  `rtc.init((2019,2,24,0,19,46,0,0)).`
But the week is always 6.

**Comment by GHPS** [comment] 2019-03-09 23:41
Duplicate of #4540

BTW: 24-2-19 was a Sunday (6 in Day-of-Week).

**Closed** 2019-04-11 09:38 UTC
