### ISSUE TITLE
Python stack corruption in finally block

### ISSUE THREAD

**Issue by jpochyla** [micropython/micropython#2455] opened 2016-09-24 12:59 UTC
```python
def foo(a, b):
    pass

def test():
    try:
        raise Exception()
    finally:
        val = 'flowers'
        foo('garbage', val)
        print(val)  # prints "garbage"

x = test()
```

If the finally handler is not inside a function issue disappears. I'm not proficient enough in uPy internals to fix this, unfortunately.

Mac unix, 32bit

**Comment by prusnak** [comment] 2016-09-24 13:09
Confirmed with Unix port on Linux 32-bit/64-bit

**Comment by dpgeorge** [comment] 2016-09-24 15:13
Thanks for the bug report, this one is a good find!  The problem is that the stack is crashing into the local variables storage (stack grows from the bottom up, local storage lives on the stack starting from the top).  It doesn't happen with @micropython.native on the test() function, so it's a problem specific to the bytecode emitter.  Basically, the emitter is not allocating/calculating enough local state for the stack.

**Comment by dpgeorge** [comment] 2016-09-27 02:49
Should be fixed as by-product of this optimisation: f040685b0cbec18feb981fdad96389a3b28b676d.  Test in 3f0c1c24528d8ce818434d8b553136d315b0d548.

**Closed by dpgeorge** 2016-09-27 02:49 UTC
Labels: bug

**Comment by prusnak** [comment] 2016-09-27 08:46
I confirm that fix works on Unix. Awesome, thanks!

**Comment by jpochyla** [comment] 2016-09-27 08:52
Amazing, thanks a lot!
