### ISSUE TITLE
utime.sleep(24*3600) sleeps only 500 seconds on ESP32

### ISSUE THREAD

**Issue by socketpair** [micropython/micropython#9304] opened 2022-09-14 01:57 UTC
**MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32**

boot.py:

```python
from utime import sleep, time

while True:
    print(time())
    sleep(24 * 3600 - 499) # without - 499 will print every 500 seconds
```

will print a line roughly at every 1-2 seconds:

```
1
2
4
6
7
9
11
...
```

 I guess, it's overflow+wraparound issue.

**Comment by socketpair** [comment] 2022-09-14 02:02
Sleeping for `24 * 3600 - 250` is expectedly sleeps for 50 seconds. So, I guess, it's overflow+wrap-around issue.

**Comment by socketpair** [comment] 2022-09-14 02:16
`sleep((24 * 3600 - 500)//5)` competes immediately

**Comment by dpgeorge** [comment] 2022-09-14 03:46
Thanks for the report, I can confirm the issue on the latest master build.

It looks like an overflow of a 32-bit integer when computing microseconds, it should be a uint64_t calculation.

**Comment by dpgeorge** [comment] 2022-09-14 04:05
Should be fixed by 0e8c2204da377e95b5000a3c708891d98cdeb69c

**Closed by dpgeorge** 2022-09-14 04:05 UTC
Labels: bug, port-esp32

**Comment by socketpair** [comment] 2022-09-14 04:22
@dpgeorge I can test the change, but I need some way of OTA update of Micropython. is it possible? If yes, some link to documentation will greatly help.

**Comment by dpgeorge** [comment] 2022-09-14 04:30
It is possible to do OTA update of ESP32 firmware using `esp32.Partition` objects (see http://docs.micropython.org/en/latest/library/esp32.html?highlight=esp32#flash-partitions).  But for that to work you first need to prepare the esp32 to have the correct OTA partition layout, which really needs a physical USB connection.
