### ISSUE TITLE
esp8266 RAM does not seem to be cleared by soft reset

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2235] opened 2016-07-12 06:19 UTC
[heavily edited] The title of this is wrong - apologies. I was misled by the ENOMEM message. The esp8266 is retaining state after a ctrl-D and it is not possible to re-run webrepl after ctrl-D.

Hardware: Adafruit Feather Huzah. Running in station mode using DHCP.
Firmware: built from source of 11th July. Boot files are unmodified.

In the following session, logged at the USB terminal from power-up, I started the webrepl but did not connect to it. I then issued ctrl-D and it would not restart, issuing ENOMEM. The mem info figures discount my initial theory about RAM, but some state is being retained through a soft reset.
```
[adminpete@axolotl]: /mnt/qnap2/data/Projects/MicroPython/micropython/esp8266/build
$ mtusb
--- Miniterm on /dev/ttyUSB0: 115200,8,N,1 ---
--- Quit: Ctrl+]  |  Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

connected with misspiggy, channel 3
dhcp client start...
ip:192.168.0.23,mask:255.255.255.0,gw:192.168.0.1

>>> import micropython
>>> micropython.mem_info()
stack: 1952 out of 8192
GC: total: 28160, used: 6256, free: 21904
 No. of 1-blocks: 20, 2-blocks: 7, max blk sz: 263, max free sz: 1363
>>> import webrepl
>>> webrepl.start()
WebREPL daemon started on ws://192.168.4.1:8266
WebREPL daemon started on ws://192.168.0.23:8266
Started webrepl in normal mode
>>> micropython.mem_info()
stack: 1952 out of 8192
GC: total: 28160, used: 9568, free: 18592
 No. of 1-blocks: 94, 2-blocks: 23, max blk sz: 263, max free sz: 1033
>>> 
PYB: soft reboot [COMMENT: ctrl-D issued at USB terminal]
could not open file 'main.py' for reading
MicroPython v1.8.1-195-gee622cc-dirty on 2016-07-11; ESP module with ESP8266
Type "help()" for more information.
>>> import micropython
>>> micropython.mem_info()
stack: 1952 out of 8192
GC: total: 28160, used: 6256, free: 21904
 No. of 1-blocks: 20, 2-blocks: 7, max blk sz: 263, max free sz: 1363
>>> import webrepl
>>> webrepl.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "webrepl.py", line 64, in start
  File "webrepl.py", line 21, in setup_conn
OSError: [Errno 12] ENOMEM
>>> micropython.mem_info()
stack: 1952 out of 8192
GC: total: 28160, used: 9552, free: 18608
 No. of 1-blocks: 88, 2-blocks: 22, max blk sz: 263, max free sz: 1033
>>> 
```

**Comment by pfalcon** [comment] 2016-07-13 08:52
Duplicate of https://github.com/micropython/micropython/issues/1896

**Closed by pfalcon** 2016-07-13 08:52 UTC
