### ISSUE TITLE
mpremote FS mount hangs with soft reboot with ESP32

### ISSUE THREAD

**Issue by jdtsmith** [micropython/micropython#7732] opened 2021-08-31 13:03 UTC
Simply mount and `C-d` to soft reboot:

```
% mpremote connect /dev/tty.usbserial-XXXX mount . repl
Local directory . is mounted at /remote
Connected to MicroPython at /dev/tty.usbserial-XXXX
Use Ctrl-] to exit this shell
>
MicroPython v1.15-835-g1fcd6e97f-dirty on 2021-08-27; ESP32 module with ESP32
Type "help()" for more information.
>>> 
MPY: soft reboot
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mpremote/main.py", line 445, in main
    do_repl(pyb, args)
  File "/usr/local/lib/python3.9/site-packages/mpremote/main.py", line 332, in do_repl
    do_repl_main_loop(
  File "/usr/local/lib/python3.9/site-packages/mpremote/main.py", line 259, in do_repl_main_loop
    pyb.soft_reset_with_mount(console_out_write)
  File "/usr/local/lib/python3.9/site-packages/mpremote/pyboardextended.py", line 612, in soft_reset_with_mount
    self.exec_(fs_hook_code)
  File "/usr/local/lib/python3.9/site-packages/mpremote/pyboard.py", line 465, in exec_
    ret, ret_err = self.exec_raw(command, data_consumer=data_consumer)
  File "/usr/local/lib/python3.9/site-packages/mpremote/pyboard.py", line 456, in exec_raw
    self.exec_raw_no_follow(command)
  File "/usr/local/lib/python3.9/site-packages/mpremote/pyboard.py", line 453, in exec_raw_no_follow
    raise PyboardError("could not exec command (response: %r)" % data)
mpremote.pyboard.PyboardError: could not exec command (response: b'R\x01')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpremote", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/mpremote/main.py", line 455, in main
    do_disconnect(pyb)
  File "/usr/local/lib/python3.9/site-packages/mpremote/main.py", line 208, in do_disconnect
    pyb.umount_local()
  File "/usr/local/lib/python3.9/site-packages/mpremote/pyboardextended.py", line 620, in umount_local
    self.exec_('uos.umount("/remote")')
  File "/usr/local/lib/python3.9/site-packages/mpremote/pyboard.py", line 467, in exec_
    raise PyboardError("exception", ret, ret_err)
mpremote.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nOSError: [Errno 22] EINVAL\r\n')

```

**Comment by dpgeorge** [comment] 2021-09-01 00:23
Closing as duplicate of #7485.

**Closed by dpgeorge** 2021-09-01 00:23 UTC
