### ISSUE TITLE
viper code fails if a function has an unused argument

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1380] opened 2015-07-13 06:32 UTC
This manifests itself in various ways, including a hard to debug case where code ran but produced incorrect results. The following example ```bar.py``` can crash the Pyboard.
```
@micropython.viper
def foo(line: int, pixelmask: int, offset: int, unused_arg: int):
    index = 0
    buf = bytearray(10)
    image = bytearray([1,1,1,1,1,1,1,1,1,1])
    for b in range(10, 0, -1):
        buf[index] = int(image[offset + b - 1])  ^ pixelmask | 0xaa
        index += 1
    print(buf)
foo(0, 0, 0, 0)
```
At the REPL if ```import bar``` is issued nothing happens (it should print the buffer contents). A subsequent ```bar.foo(0,0,0,0)``` crashes the board. Unused arguments should either be ignored or a compile time error should be issued.

**Comment by dpgeorge** [comment] 2015-07-23 13:13
The problem is that viper functions can only take up to 3 arguments.  Now fixed so they can take up to 4 arguments.  Taking 5 or more requires a bit more work :)

**Closed by dpgeorge** 2015-07-23 13:13 UTC
