### ISSUE TITLE
'compiler' reports wrong line number when loop variable previously not defined

### ISSUE THREAD

**Issue by rhubarbdog** [micropython/micropython#4186] opened 2018-09-24 22:54 UTC
I have this program which doesn't set local variable `pressed` before testing it in a `while not pressed:` statement.
```
import pyb

def function():
    pyb.delay(1000)

    return 1

def main():

    yellow = pyb.LED(3)
    yellow.on()

    while not pressed:
        if function is None:
            pressed = True

        yellow.toggle()

    yellow.off()

main()
```

When i try to run it it crashes reporting line 17 has the error of `NameError: local variable referenced before assignment`. the offending while statement is line 13. line 17 reads `yellow.toggle()`

```
PYB: sync filesystems
PYB: soft reboot
Traceback (most recent call last):
  File "main.py", line 22, in <module>
  File "main.py", line 17, in main
NameError: local variable referenced before assignment
```

**Comment by dpgeorge** [comment] 2018-09-24 23:56
This is a duplicate of #1104, also documented here: http://docs.micropython.org/en/latest/pyboard/genrst/builtin_types.html?highlight=line%20number#exception-in-while-loop-condition-may-have-unexpected-line-number

**Closed by dpgeorge** 2018-09-24 23:56 UTC
