### ISSUE TITLE
root path problem on esp8266-ota-20170304-v1.8.7-347-g3ab6aa3

### ISSUE THREAD

**Issue by pacmac** [micropython/micropython#2933] opened 2017-03-04 09:45 UTC
Spent ages trying to figure out while I was unable to run my apps which use filesystem read.

This release appears to think that the root folder is /flash, wheras esp8266-20170108-v1.8.7 assumes it to be /

I believe that /flash is the root folder for piboard and esp32 ??

I have reverted back to esp8266-20170108-v1.8.7.

**Comment by pfalcon** [comment] 2017-03-04 11:01
Duplicate of https://github.com/micropython/micropython/issues/2850.

> esp8266-20170108-v1.8.7 

is the current release, there were no releases since it.

**Closed by pfalcon** 2017-03-04 11:01 UTC
