### ISSUE TITLE
uctypes.sizeof should have explicit layout_type argument

### ISSUE THREAD

**Issue by jpochyla** [micropython/micropython#3101] opened 2017-05-19 10:26 UTC
Right now it's impossible to create a buffer with exact size in case of structs with layout different than `LAYOUT_NATIVE`. Example code:

```python
sz = uctypes.sizeof(desc)
buf = bytearray(sz)  # buf gets a length of a struct with added padding, which is too big
struct = uctypes.struct(uctypes.addressof(buf), desc, uctypes.BIG_ENDIAN)
```

If it looks sensible, i'll send a PR right away.

**Comment by pfalcon** [comment] 2017-05-31 19:48
The problem is well-spotted and needs fixing. But please first come up with a proposal of new API for this.

**Comment by prusnak** [comment] 2018-01-01 19:43
Seems this one was forgotten. We use the following patch for quite some time, which adds extra parameter to sizeof, which allows to pass the layout:

https://github.com/trezor/micropython/commit/6c5f953c797ff32911901215b8d0b7615d84ece8

**Comment by pfalcon** [comment] 2018-10-24 15:14
This was implemented with a somewhat different signature, better fitting the intended API of the module in 2411f42ccba561affc0882f8983811b9d8c02b94.

**Comment by dpgeorge** [comment] 2018-10-30 01:09
Closing because this was implemented.

**Closed by dpgeorge** 2018-10-30 01:09 UTC
Labels: prio-med, triaged
