### ISSUE TITLE
webrepl on PICO_W

### ISSUE THREAD

**Issue by villeneuve** [micropython/micropython#8961] opened 2022-07-26 13:56 UTC
First thanks guys for giving us this excellent micropython.
To be consistent with pull request [#8931](https://github.com/micropython/micropython/pull/8931)   I think the following change is needed:
must be added:
`include("$(MPY_DIR)/extmod/webrepl/manifest.py")`
to file: `micropython/ports/rp2/boards/manifest.py` (or maybe another file is more suitable?)
Because currently webrepl works well on ESP8266 but not on PICO_W (no module named 'webrepl')
Thanks
PS: Sorry for raising an issue instead of a pull request, I'm not familiar with that.

**Comment by jimmo** [comment] 2022-07-26 14:35
Duplicate of #8928

**Closed by jimmo** 2022-07-26 14:35 UTC
Labels: bug

**Comment by villeneuve** [comment] 2022-07-27 10:57
Oh! Sorry I misunderstood. Because the last modification (PR #8931) is included in the ESP8266 port, I thought that the choice about the following point (issue #8928) had been done, in favor of the first option.

```
We need to decide:

- Should we freeze the webrepl Python files on all boards that include the webrepl C support
 (which is now controlled by MICROPY_PY_NETWORK)

- or. Make webrepl something that can be installed optionally (upip, etc) and document that, 
  and leave it to specific boards that want to freeze it.

```

**Comment by jimmo** [comment] 2022-07-28 00:14
#8931 is a separate issue and is a fix to webrepl itself, it just came up in the discussion of #8928 (I wanted to make sure that if we enabled webrepl that it was actually usable).

I don't think #8928 has been decided, except for the specific case of the PICO_W, although the PR still needs to be made to actually do that. In the meantime though you can just copy webrepl.py and webrepl_setup.py to your device.
