### ISSUE TITLE
esp32: Webserver Socket stops responding after a minute.

### ISSUE THREAD

**Issue by mispacek** [micropython/micropython#15844] opened 2024-09-13 14:23 UTC
### Port, board and/or hardware

esp32 port, ESP32 and ESP32C3

ESP32 (lolin32-Lite, esp32 devkit v1)  and ESP32C3 (esp32c3 supermini)
both board have same issues

### MicroPython version
MicroPython v1.23.0 on 2024-06-02; ESP32C3 module with ESP32C3
in older versions than MicroPython v1.20.0 code works fine withou issues

MicroPython v1.19.1 works OK
MicroPython v1.20.0 works OK
MicroPython v1.21.0 NOT working
MicroPython v1.22.0 NOT working
MicroPython v1.23.0 NOT working

### Reproduction

Copy content of zip file to your ESP device. Set correct SSID and Password and reset your board.
[issue.zip](https://github.com/user-attachments/files/16995089/issue.zip)

The web server will offer you index.html, which cyclically send requests to server and server answers back.
in terminal you can see positions of virtual joysticks on webpage.
![image](https://github.com/user-attachments/assets/185af8c7-6922-490a-8294-11c02679d83f)

After about a minute, the server stops responding. There is enough free RAM, I don't know where the problem is, everything works correctly on older versions.

There is another version of the web server available in the Zip archive, without the use of threads, but the problem is exactly the same.

### Expected behaviour

I expect that the server will behave the same in all versions. It should respond indefinitely to web browser requests.

### Observed behaviour

In Chrome, using developer tools, I check the responses from the server. After 1-5 minutes, the server stops responding and sometimes restarts.
![image](https://github.com/user-attachments/assets/76e40f0c-d6b3-4562-9fb9-93b806841402)

### Additional Information

Web server must run in background, without blocking of REPL and WebRepl

Code of webserver with threads:
```
import network
import usocket
import _thread
from os import stat, listdir
from time import sleep_ms
import gc


class WebServer:
    def __init__(self, web_folder='/www', port=80):
        self.WEB_FOLDER = web_folder
        self.MIMETYPES = {
            "txt"   : "text/plain",
            "htm"   : "text/html",
            "html"  : "text/html",
            "css"   : "text/css",
            "csv"   : "text/csv",
            "js"    : "application/javascript",
            "xml"   : "application/xml",
            "xhtml" : "application/xhtml+xml",
            "json"  : "application/json",
            "zip"   : "application/zip",
            "pdf"   : "application/pdf",
            "ts"    : "application/typescript",
            "ttf"   : "font/ttf",
            "jpg"   : "image/jpeg",
            "jpeg"  : "image/jpeg",
            "png"   : "image/png",
            "gif"   : "image/gif",
            "svg"   : "image/svg+xml",
            "ico"   : "image/x-icon",
            "cur"   : "application/octet-stream",
            "tar"   : "application/tar",
            "tar.gz": "application/tar+gzip",
            "gz"    : "application/gzip",
            "mp3"   : "audio/mpeg",
            "wav"   : "audio/wav",
            "ogg"   : "audio/ogg"
        }
        self.webserv_sock = None
        self.url_handlers = {}
        self.port = port

    def _file_exists(self, path):
        try:
            stat(path)
            return True
        except:
            return False

    def get_mime_type(self, filename):
        try:
            _, ext = filename.rsplit(".", 1)
            return self.MIMETYPES.get(ext, "application/octet-stream")
        except:
            return "application/octet-stream"
        
    def read_in_chunks(self, file_object, chunk_size=1024):
        while True:
            data = file_object.read(chunk_size)
            if not data:
                break
            yield data

    def serve_file(self, client, path):
        try:
            
            if path.startswith("/*GET_FILE"):
                file_path = path.replace("/*GET_FILE", "")
            else:
                if path == "/":
                    path = "/index.html"
                if '?' in path:
                    path = path.split('?')[0]
                file_path = self.WEB_FOLDER + path
            
            mime_type = self.get_mime_type(file_path)
            filestatus = 0 # 0=Not found  1=Found  2=found in GZip

            if self._file_exists(file_path + '.gz'):
                filestatus = 2
                file_path += '.gz'
            elif self._file_exists(file_path):
                filestatus = 1
                        
            if filestatus > 0:
                with open(file_path, 'rb') as file:
                    client.write(b'HTTP/1.1 200 OK\r\n')
                    client.write(b"Content-Type: " + mime_type.encode() + b"\r\n")
                    if filestatus == 2:
                        client.write(b'Content-Encoding: gzip\r\n')
                    client.write(b'\r\n')
                    for piece in self.read_in_chunks(file):
                        client.write(piece)
            else:
                client.write(b"HTTP/1.0 404 Not Found\r\n\r\nFile not found.")
        except OSError as e:
            print("OSError:", e)
            client.write(b"HTTP/1.0 500 Internal Server Error\r\n\r\nInternal error.")
        except Exception as e:
            print("Exception:", e)
            client.write(b"HTTP/1.0 500 Internal Server Error\r\n\r\nInternal error.")

    def handle(self, pattern):
        """Decorator to register a handler for a specific URL pattern."""
        def decorator(func):
            self.url_handlers[pattern] = func
            return func
        return decorator

    def client_handler(self, client):
        try:
            gc.collect()
            sleep_ms(0)
            request = client.recv(2048)
            if request:
                _, path, _ = request.decode("utf-8").split(" ", 2)
                for pattern, handler in self.url_handlers.items():
                    if path.startswith(pattern):
                        try:
                            gc.collect()
                            handler(client, path, request)
                        except Exception as e:
                            print("Handler Exception:", e)
                        client.close()
                        return
                # Default file serving if no handler matches
                self.serve_file(client, path)
        except Exception as e:
            sleep_ms(0)
            #print("Webserver Exception:", e)
        finally:
            client.close()

    def web_thread(self):
        while True:
            try:
                cl, addr = self.webserv_sock.accept()
                cl.settimeout(2)  # time in seconds
                self.client_handler(cl)
            except Exception as ex:
                sleep_ms(0)

    def start(self):
        addr = usocket.getaddrinfo('0.0.0.0', self.port)[0][-1]
        self.webserv_sock = usocket.socket()
        self.webserv_sock.setsockopt(usocket.SOL_SOCKET, usocket.SO_REUSEADDR, 1)
        self.webserv_sock.bind(addr)
        self.webserv_sock.listen(5)
        _thread.start_new_thread(self.web_thread, ())
        for interface in [network.AP_IF, network.STA_IF]:
            wlan = network.WLAN(interface)
            if not wlan.active():
                continue
            ifconfig = wlan.ifconfig()
            print("Web server spusten na adrese {}:{}".format(ifconfig[0], self.port))

    def stop(self):
        if self.webserv_sock:
            self.webserv_sock.close()
 
```

Code of webserver without threads:

```
import network
import socket
from os import stat, listdir
from time import sleep_ms
import gc
from micropython import alloc_emergency_exception_buf

# Define constant for registering the handler function
_SO_REGISTER_HANDLER = 20

class WebServer:
    def __init__(self, web_folder='/www', port=80):
        self.WEB_FOLDER = web_folder
        self.MIMETYPES = {
            "txt"   : "text/plain",
            "htm"   : "text/html",
            "html"  : "text/html",
            "css"   : "text/css",
            "csv"   : "text/csv",
            "js"    : "application/javascript",
            "xml"   : "application/xml",
            "xhtml" : "application/xhtml+xml",
            "json"  : "application/json",
            "zip"   : "application/zip",
            "pdf"   : "application/pdf",
            "ts"    : "application/typescript",
            "ttf"   : "font/ttf",
            "jpg"   : "image/jpeg",
            "jpeg"  : "image/jpeg",
            "png"   : "image/png",
            "gif"   : "image/gif",
            "svg"   : "image/svg+xml",
            "ico"   : "image/x-icon",
            "cur"   : "application/octet-stream",
            "tar"   : "application/tar",
            "tar.gz": "application/tar+gzip",
            "gz"    : "application/gzip",
            "mp3"   : "audio/mpeg",
            "wav"   : "audio/wav",
            "ogg"   : "audio/ogg"
        }
        self.webserv_sock = None
        self.url_handlers = {}
        self.port = port
        self.client_sockets = []

    def _file_exists(self, path):
        try:
            stat(path)
            return True
        except:
            return False

    def get_mime_type(self, filename):
        try:
            _, ext = filename.rsplit(".", 1)
            return self.MIMETYPES.get(ext, "application/octet-stream")
        except:
            return "application/octet-stream"
        
    def read_in_chunks(self, file_object, chunk_size=1024):
        while True:
            data = file_object.read(chunk_size)
            if not data:
                break
            yield data

    def serve_file(self, client, path):
        try:
            
            if path.startswith("/*GET_FILE"):
                file_path = path.replace("/*GET_FILE", "")
            else:
                if path == "/":
                    path = "/index.html"
                if '?' in path:
                    path = path.split('?')[0]
                file_path = self.WEB_FOLDER + path
            
            mime_type = self.get_mime_type(file_path)
            filestatus = 0 # 0=Not found  1=Found  2=found in GZip

            if self._file_exists(file_path + '.gz'):
                filestatus = 2
                file_path += '.gz'
            elif self._file_exists(file_path):
                filestatus = 1
                        
            if filestatus > 0:
                with open(file_path, 'rb') as file:
                    client.write(b'HTTP/1.1 200 OK\r\n')
                    client.write(b"Content-Type: " + mime_type.encode() + b"\r\n")
                    if filestatus == 2:
                        client.write(b'Content-Encoding: gzip\r\n')
                    client.write(b'\r\n')
                    for piece in self.read_in_chunks(file):
                        client.write(piece)
            else:
                client.write(b"HTTP/1.0 404 Not Found\r\n\r\nFile not found.")
        except OSError as e:
            print("OSError:", e)
            client.write(b"HTTP/1.0 500 Internal Server Error\r\n\r\nInternal error.")
        except Exception as e:
            print("Exception:", e)
            client.write(b"HTTP/1.0 500 Internal Server Error\r\n\r\nInternal error.")

    def handle(self, pattern):
        """Decorator to register a handler for a specific URL pattern."""
        def decorator(func):
            self.url_handlers[pattern] = func
            return func
        return decorator

    
    def accept_websocket(self, sock):
        try:
            client_sock, client_addr = sock.accept()
            #client_sock.setblocking(False)
            client_sock.settimeout(2)
            client_sock.setsockopt(socket.SOL_SOCKET, _SO_REGISTER_HANDLER, self.client_handler)
            self.client_sockets.append(client_sock)
            # Debug output
            #print("Received new connection from:", client_addr)
            #print(self.client_sockets)
        except Exception as e:
            print("Error accepting connection:", e)
    
    
    
    
    def client_handler(self, client_sock):
        try:
            request = client_sock.recv(2048)
            #print(request)
            if request:
                _, path, _ = request.decode("utf-8").split(" ", 2)
                for pattern, handler in self.url_handlers.items():
                    if path.startswith(pattern):
                        try:
                            gc.collect()
                            handler(client_sock, path, request)
                        except Exception as e:
                            print("Handler Exception:", e)
                        self.close_client(client_sock)
                        return
                # Default file serving if no handler matches
                self.serve_file(client_sock, path)
            self.close_client(client_sock)
        except Exception as e:
            print("Error in client_handler:", e)
            self.close_client(client_sock)

    def close_client(self, client_sock):
        try:
            client_sock.setsockopt(socket.SOL_SOCKET, _SO_REGISTER_HANDLER, None)
            client_sock.close()
        except Exception as e:
            print("Error closing client socket:", e)
        finally:
            if client_sock in self.client_sockets:
                self.client_sockets.remove(client_sock) 

    def start(self):
        alloc_emergency_exception_buf(100)
        addr = socket.getaddrinfo('0.0.0.0', self.port)[0][-1]
        self.webserv_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.webserv_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.webserv_sock.bind(addr)
        self.webserv_sock.listen(1)
        self.webserv_sock.settimeout(2)
        self.webserv_sock.setsockopt(socket.SOL_SOCKET, _SO_REGISTER_HANDLER, self.accept_websocket)
        for interface in [network.AP_IF, network.STA_IF]:
            wlan = network.WLAN(interface)
            if not wlan.active():
                continue
            ifconfig = wlan.ifconfig()
            print("Web server started at address {}:{}".format(ifconfig[0], self.port))

    def stop(self):
        if self.webserv_sock:
            self.webserv_sock.setsockopt(socket.SOL_SOCKET, _SO_REGISTER_HANDLER, None)
            self.webserv_sock.close()
        for client_sock in self.client_sockets:
            self.close_client(client_sock)

```

### Code of Conduct

Yes, I agree

**Comment by TRadigk** [comment] 2024-09-14 06:23
Hi,

I've had the same issue and no solution for that. But since I already was going for seed xiao ESP32C3, I was able to replace it with an ESP32S3 (also seed xiao), which is a little bit more expensive but has the same footprint and mostly same pin configuration.

In my investigations I also found out:
long requests (256 Bytes) lead to immediate "hang", the device stops responding to "ping" requests. With wireshark I found out that the device always answers the HTTP ACK, but might not send data. If helpful I could provide this additional info in more detail.

**Comment by xuancong84** [comment] 2024-09-15 15:35
I also encounter the same problem on esp32c3, except that instead of one minute, the web server stops responding after a random period of time between a few minutes and one day or so. However, `ping` continues to work.

The randomness of this bug makes it very difficult to solve.

**Comment by dpgeorge** [comment] 2024-09-16 02:05
Thanks for the clear report and the reproduction.  Using the instructions in the original report, with ESP32_GENERIC firmware, IDF 5.2.2 and a recent master MicroPython `v1.24.0-preview-309-gf1bdac375` I was able to reproduce the issue: after around 1 minute of having the webpage open and accessing the ESP32 server, TCP connections would stop.  They would eventually resume after a few minutes.

This looks like the same root cause as with the issue #12819.  It's because TCP sockets are remaining open on the ESP32 server for up to 2 minutes.

I tested the fix suggested in #12819 which is to add `CONFIG_LWIP_TCP_MSL=6000` to `ports/esp32/boards/sdkconfig.base`  That fixes the issue for me, both the threading and non-threading version of the webserver (v1 and v2) work fine with that adjusted MSL (at least, I can run for much longer and don't see any issues).

I also made a simpler client program in Python to show the same issue, so you don't need to test with a web browser.  Just run this on the host PC:
```py
import time
import requests

IP = '<ip of esp32>'

for i in range(1000):
    r = requests.get(f'http://{IP}/*JOY;{i};0;0;0;0;0')
    r.close()
    time.sleep(0.15)
```
Eventually that will stop sending requests.

**Comment by dpgeorge** [comment] 2024-09-16 02:45
The problem does not happen on a PYBD-SF6 (and presumably all other bare-metal lwIP MicroPython boards) because those boards have a very limited amount of static memory allocated to lwIP, and lwIP is then forced to close and reuse sockets that are sitting in the TIME-WAIT state.

In particular, in the `tcp_alloc()`, the "tcp_alloc: killing off oldest TIME-WAIT connection" debug message is printed (and hence `tcp_kill_timewait()` run) on PYBD-SF6 but not on ESP32.

Ideally we need a way on ESP32 to limit the maximum number of opened PCBs, and force `tcp_alloc()` to reclaim PCBs when that limit is reached.  But I'm not sure how to do that.  Somehow we need to hook into the `memp_malloc(MEMP_TCP_PCB)` call and return NULL when the maximum number of PCBs is reached.

**Comment by TRadigk** [comment] 2024-09-16 07:00
Hi Damien,
I couldn't encounter the issue on ESP32 S3 (with 8 MB) of Ram in **1000** subsequent requests, where the ESP32 C3 hang up after like 20. Since you're changing something in the ESP32 port, should the issue also occur on the ESP32S3 but due to much more available RAM way later?

**Comment by dpgeorge** [comment] 2024-09-19 01:31
> should the issue also occur on the ESP32S3 but due to much more available RAM way later?

Probably not, because the TCP socket waits in TIME-WAIT state for 2 minutes, after which it is reclaimed.  So there's probably enough RAM to allocate a few thousand sockets before they need to be recycled, at which point the 2 minutes from the first sockets has passed and their memory is freed.

**Comment by projectgus** [comment] 2024-09-26 04:58
This looks like the same port reuse problem previously described here: https://github.com/micropython/micropython/issues/12819#issuecomment-1797336596 - the connection stalls once the same port is reused, and only unstalls later 

![image](https://github.com/user-attachments/assets/168e4472-c80b-42a7-8c2c-21c0393e2c8a)

Going to try and reproduce this without MicroPython, as it seems like an ESP-IDF/LWIP TCP/IP stack bug...

**Comment by projectgus** [comment] 2024-09-26 05:06
(Sorry for duplicate post, previous screenshot was wrong.)

I can reproduce using Damien's client code and the provided files, and I see it getting stuck when the client reuses the same port number. Same as described here: https://github.com/micropython/micropython/issues/12819#issuecomment-1797336596

![image](https://github.com/user-attachments/assets/bb57f9da-f819-413a-ad54-7480f2f621f9)

Eventually the existing socket with this port ends TIME-WAIT and everything starts working again.

**Comment by dpgeorge** [comment] 2024-09-26 05:32
Testing again with Wireshark enabled, I can confirm that a TCP port number is being reused, and that's exactly the point at which the esp32 server stops responding.  And the esp32 is ACK'ing the RST.

I actually tested by using `examples/network/http_server.py` as the server code on the esp32.  So it looks like the issue is very easy to reproduce with any server code.

**Comment by projectgus** [comment] 2024-09-26 05:56
I think the problem is that the socket isn't being properly closed on the MicroPython side.

The capture in the screenshot above is incomplete, but even on a complete capture I only see the client sending a FIN but the server (MicroPython) never sends a FIN packet back. This is despite the server calling close on the socket.

On the ESP-IDF http server the client initiates the close with a FIN and then the server sends a FIN back, and the problem doesn't reoccur.

There is a specific sequence to closing HTTP sockets that should be followed, although I think even a server which doesn't follow that sequence shouldn't be seeing this behaviour.

**Comment by dpgeorge** [comment] 2024-09-26 06:48
What's the correct way to close?  We call `lwip_close(fd)`.  Maybe we need to call the higher level function `close()`?

**Comment by projectgus** [comment] 2024-09-26 06:58
I think MicroPython is doing the right thing, it's just somehow LWIP is transtioning the socket to TIME-WAIT without ever sending a FIN packet... It's quite odd, it might be a race condition with the timing of the client sending its FIN and the server calling `close()` on the socket...

**Comment by projectgus** [comment] 2024-10-01 07:16
I've hidden the comments above because I was reading the WireShark output wrong, my mistake!

The underlying problem is the [same as described here](https://github.com/micropython/micropython/issues/12819#issuecomment-1797336596). The conditions are:

1. The server (MicroPython) closes the connection first. If the client closes the connection first, it doesn't enter TIME-WAIT on the server so the problem doesn't trigger. However if the server closes the connection first then it *does* enter TIME-WAIT.
2. The client opens a new connection with the same source port, before the TIME-WAIT has expired (two minutes I think, by default).

What happens then is that the client sends TCP SYN, the server sends TCP ACK, the client recognises the ACK is invalid because it belongs to the old connection and sends TCP RST, but the server ignores this ([required for RFC1337](https://github.com/espressif/esp-lwip/blob/2.1.2-esp/src/core/tcp_in.c#L745)). It will stay stuck like this until after the 2 minutes expires, although the client usually times out first.

## Reproduce without MicroPython

I can reproduce this in C if I modify the [tcp_server example](https://github.com/espressif/esp-idf/tree/master/examples/protocols/sockets/tcp_server) to close the socket after it sends the first response back to the client.

ESP-IDF server patch:

```patch
diff --git i/examples/protocols/sockets/tcp_server/main/tcp_server.c w/examples/protocols/sockets/tcp_server/main/tcp_server.c
index 5f1c284960..b4ac5c97b3 100644
--- i/examples/protocols/sockets/tcp_server/main/tcp_server.c
+++ w/examples/protocols/sockets/tcp_server/main/tcp_server.c
@@ -59,6 +59,7 @@ static void do_retransmit(const int sock)
                 to_write -= written;
             }
         }
+        break;
     } while (len > 0);
 }

```

Client program to repro with tcp_server:

```python
#!/usr/bin/env python
import socket
import time

HOST="10.42.0.150"  # <-- Server IP goes here
PORT=3333

while True:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(5)  # so fails when bug triggers
    s.connect((HOST, PORT))

    s.send(b"ABCD")
    print(time.time(), s.recv(4))
    s.close()
```

## Workarounds

I can't find a perfect workaround, but I think any of these would work:

* Set a timeout on the client side and retry when the connect times out. For example, [if doing this from JavaScript](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout).
* Slow down the rate of requests so that ports aren't reused within a two minute window. It'd be a big change, but a long lived WebSocket could be a good fit for this kind of frequent data request.
* Implement HTTP/1.1 connection reuse for the server. (Another big change.)
* Have the client close the connection, not the server. Unfortunately I think this is only possible by implementing proper HTTP/1.1. The kind of server attached to this issue is an HTTP/1.0 style ["close-delimited response message"](https://www.rfc-editor.org/rfc/rfc9112.html#name-message-body-length), i.e. the server needs to Close the connection because this is how the client knows there is no more data. Doing it in the recommended HTTP/1.1 way means setting `Connection: close` and a `Content-Length:` header, so it's a lot more complex...

## Fixes?

Linux and OpenBSD servers don't have this problem because if they see an out-of-sequence SYN for a TIME-WAIT socket then they allow it as a new connection. [OpenBSD code](https://github.com/openbsd/src/blob/477ac4f17e6a6b377943ecf8e34bc324defc64a6/sys/netinet/tcp_input.c#L1226), [Linux code](https://github.com/torvalds/linux/blob/master/net/ipv4/tcp_minisocks.c#L173). 

We could request LWIP support be added to do the same thing. The issues I can see are:

* OpenBSD and Linux also check timestamps by default, which is recommended approach to avoid "TIME-WAIT assassination" (see RFC1337). LWIP doesn't implement the embedded timestamp option.
* The way LWIP is structured in the code then it's kind of fiddly to recycle a TIME-WAIT socket.
* Due to the above, I suspect Espressif would only add it to their esp-lwip fork if upstream LWIP agreed it was a good idea. And the upstream LWIP is not particularly active.

A simpler/quicker "fix" would to be to immediately clean up the socket if an RST is received in TIME-WAIT (i.e. [change this bit](https://github.com/espressif/esp-lwip/blob/2.1.2-esp/src/core/tcp_in.c#L751)). However this does open the possibility of "TIME-WAIT assassination", trading one bug for a worse one in some cases (old data arrives on new socket :scream_cat:).

**Comment by projectgus** [comment] 2024-10-01 07:51
@mispacek can you please try flashing this ESP32-C3 build and see if you can still reproduce the problem? 
[ESP32_GENERIC_C3_LWIP_RST_patch.zip](https://github.com/user-attachments/files/17201313/ESP32_GENERIC_C3_LWIP_RST_patch.zip).

(If anyone else wants to test on a different board, let me know.)

This *isn't a fix*, it's the hacky fix-with-othert-issues mentioned at the very end of the last comment. Patch is https://github.com/projectgus/esp-lwip/tree/hack-cleanup-time-wait-on-rst - but if this build fixes the problem then it at least confirms this is the issue.

**Comment by ma261065** [comment] 2024-10-01 20:03
Isn't rfc1337 saying that immediately cleaning up the socket if an RST is received in TIME-WAIT is the fix?

```
Fixes for TWA Hazards

   We discuss three possible fixes to TCP to avoid these hazards.

   (F1) Ignore RST segments in TIME-WAIT state.
```

**Comment by projectgus** [comment] 2024-10-01 23:40
> Isn't rfc1337 saying that immediately cleaning up the socket if an RST is received in TIME-WAIT is a fix for TWA, rather than 'opening up the possibility of TWA' as you said?

My understanding is that TIME-WAIT assassination is when the TCP stack cleans up the socket too early (the bad effect being that after this, additional out-of-band packets might be delivered to the application on a new socket). The fix of ignoring RST means ignoring the RST packet and doing nothing, rather than cleaning up the socket early.

**Comment by projectgus** [comment] 2024-10-01 23:50
One more contributing factor to this is that ESP-IDF doesn't limit the number of sockets in TIME-WAIT. The config option that should limit this is not effective (see https://github.com/espressif/esp-idf/issues/9670).

If that bug was fixed then this problem would happen much less often because TIME-WAIT sockets would be cleaned up more rapidly when there are a lot of short lived connections. However, I think the problem might still happen sometimes - in my packet captures sometimes Linux reuses the same source port very quickly, for whatever reason.

**Comment by projectgus** [comment] 2024-10-02 05:46
Candidate fix in the linked PR, and I've posted some builds there if anyone is able to test: https://github.com/micropython/micropython/pull/15952#issuecomment-2387676282

**Closed** 2024-10-10 07:04 UTC
Labels: bug, port-esp32
