### ISSUE TITLE
BLE disable / enable not working properly on unix port

### ISSUE THREAD

**Issue by andrewleech** [micropython/micropython#6656] opened 2020-11-27 00:47 UTC
I tried to add a disable/re-enable after disconnect in an example test script 
```
    def _irq(self, event, data):
        ...
        elif event == _IRQ_CENTRAL_DISCONNECT:
            conn_handle, _, _ = data
            micropython.schedule(self.on_disconnect, None)

    def on_disconnect(self, *_):
        self._ble.active(False)
        time.sleep(1)
        self._ble.active(True)
        time.sleep(1)
        self._advertise()
```
This failed on the `self._ble.active(True)` line with a `OSError: [Errno 110] ETIMEDOUT`

I'll investigate this later once other BLE issues are out of the way

**Comment by dpgeorge** [comment] 2020-11-27 01:02
I think the issue is that you cannot run `ble.active()` in a schedule context, because that runs at a higher priority than NimBLE.

**Comment by andrewleech** [comment] 2020-11-27 01:06
Ah, ha yes of course, thanks for that. On my other platform this call is done from a usb command, so not from the ble callbacks / schedule.
Is there a way for code to detect its in schedule so that a clearer exception could be raised?

**Comment by jonnor** [comment] 2024-09-13 20:31
The main problem here seems to have been resolved. Perhaps we can close this issue?

**Closed** 2024-09-14 06:44 UTC
Labels: proposed-close
