### ISSUE TITLE
fat filesystem can rename a directory inside of itself

### ISSUE THREAD

**Issue by jepler** [micropython/micropython#9313] opened 2022-09-14 13:47 UTC
Over in Circuitpython, we noticed that (via the web workflow, though it's equally possible in the repl) it was possible to rename a directory "inside of itself", making the filesystem corrupt.

I created a failing test for this, specifically against the fat filesystem implementation: https://github.com/micropython/micropython/compare/master...jepler:circuitpython:vfs-fat-island?expand=1#files_bucket

I don't know whether other filesystems like littlefs are affected, I didn't test it.

**Comment by jepler** [comment] 2022-09-14 13:49
@makermelissa tagging you on this, I only saw some of the discussion about this and you may have more info to contribute. Looks like you are working on a fix for CP at https://github.com/adafruit/circuitpython/pull/6883 as well.

**Comment by dhalbert** [comment] 2022-09-14 13:51
I think #4177 may cover this.

**Comment by jepler** [comment] 2022-09-14 15:00
Yeah, I failed to find it in my search, thanks

**Comment by makermelissa** [comment] 2022-09-14 15:14
Ah ok. I didn't realize it was happening in the REPL or with MicroPython too.

**Comment by jonnor** [comment] 2024-09-29 12:09
Duplicate of https://github.com/micropython/micropython/issues/4177

**Closed by jonnor** 2024-09-29 12:09 UTC
Labels: bug
