### ISSUE TITLE
ENOMEM on request('post'...) with 1.21.0 version

### ISSUE THREAD

**Issue by abegines** [micropython/micropython#12790] opened 2023-10-24 10:54 UTC
### Discussed in https://github.com/orgs/micropython/discussions/12788

<div type='discussions-op-text'>

<sup>Originally posted by **abegines** October 24, 2023</sup>
Hello,
I've a device reporting data through https to server (it's mandatory use https)

The the device is based on ESP32 devkit c1 v4, Chip is ESP32-D0WDQ6 (revision v1.0)

When i was on micropython `1.19.1` all works fine, with `1.20.0` also fine...
But if i upgrade to `1.21.0` i get ENOMEM exceptions inside wrap_socket when I call `urequests.request('post', ...`

For comparing memory usage and so, i write this function:

```
def meminfo(title):
    print(title, '===================================================')
    print(os.uname())
    print('mem_free:', gc.mem_free())
    print('mem_alloc:', gc.mem_alloc())
    micropython.mem_info()
    print(title, '------------------------------------------------------------------------')

```
Then I call it JUST AFTER connecting to the wifi and do gc.collect() and JUST BEFORE calling the very first request('post') with this block of code:

```
#wifi connected just now
gc.collect()
meminfo('First post after wifi connected')
response= urequests.request( 'POST', 'https://miservername.com/api/getEntorno', json = {"a":25})
print (response.status_code, response.text)
```

As said...

When I run on 1.19.1 it shows...

```
WIFI connected, trying to post... ==================================================================================================
(sysname='esp32', nodename='esp32', release='1.19.1', version='v1.19.1 on 2022-06-18', machine='ESP32 module with ESP32')
mem_free: 50096
mem_alloc: 61072
stack: 1264 out of 15360
GC: total: 111168, used: 61072, free: 50096
 No. of 1-blocks: 596, 2-blocks: 175, max blk sz: 282, max free sz: 361
WIFI connected, trying to post... --------------------------------------------------------------------------------------------------
200 {"err":false,"result":{"entorno":"PROD","horaz":"2023-10-24T08:54:19.494Z","horaoffset":-120}}
```

When i run on 1.20.0 it shows...

```
WIFI connected, trying to post... ===========================================
(sysname='esp32', nodename='esp32', release='1.20.0', version='v1.20.0 on 2023-04-26', machine='ESP32 module with ESP32')
mem_free: 49728
mem_alloc: 61440
stack: 1264 out of 15360
GC: total: 111168, used: 61440, free: 49728
 No. of 1-blocks: 609, 2-blocks: 174, max blk sz: 282, max free sz: 365
WIFI connected, trying to post... ----------------------------------------------------------
200 {"err":false,"result":{"entorno":"PROD","horaz":"2023-10-24T08:57:12.151Z","horaoffset":-120}}
```

When I run on 1.21.0 it shows...

```
WIFI connected, trying to post... ============================================
(sysname='esp32', nodename='esp32', release='1.21.0', version='v1.21.0 on 2023-10-05', machine='Generic ESP32 module with ESP32')
mem_free: 85920
mem_alloc: 60512
stack: 1264 out of 15360
GC: total: 128000, used: 60512, free: 67488, max new split: 18432
 No. of 1-blocks: 577, 2-blocks: 173, max blk sz: 282, max free sz: 2638
WIFI connected, trying to post... -------------------------------------------------------------------------
[Errno 12] ENOMEM
```

Suprisingly on 1.21.0 we have 128000 of GC total, instead of 111168 in previous versions... but it fails when trying to post with https.
Have you any cue about that?

Thanks!</div>

**Comment by jimmo** [comment] 2023-10-25 03:46
Closing as duplicate of the existing discussion. I'll provide more info there.

**Closed by jimmo** 2023-10-25 03:46 UTC
