### ISSUE TITLE
Webrepl protocol crashes on unicode

### ISSUE THREAD

**Issue by rikte88** [micropython/micropython#3342] opened 2017-10-02 20:36 UTC
Try in webrepl
>>> print('\u0414')
Disconnected

The returned data is not a valid websocket text frame, but sent as such. This causes google chrome to disconnect. Maybe endoce terminal I/O as json, or send as binary data instead of text frames?

**Comment by dpgeorge** [comment] 2017-10-03 08:41
Thanks for the report, I confirm that it's a problem (tested with Firefox).

WebSocket text frames allow data to be utf-8 encoded, so that part is OK.  The issue is that the uPy code currently sends one byte at a time over the WebSocket and so splits utf-8 data into 1-byte frames.  This is then rejected by the browser.

It might be possible to fix it by using the fragment feature of WebSocket frames to say that the rest of the utf-8 data is coming in later frames.  Or it could be fixed by sending the whole utf-8 character at once.

**Comment by dpgeorge** [comment] 2017-10-03 08:44
> Or it could be fixed by sending the whole utf-8 character at once.

See #3343 for such a fix.

**Comment by dpgeorge** [comment] 2017-10-03 12:27
The fix for this was merged.

**Closed** 2017-10-03 12:27 UTC
