### ISSUE TITLE
Timer: deinit(): lag

### ISSUE THREAD

**Issue by PrimeTime416** [micropython/micropython#8934] opened 2022-07-20 02:07 UTC
Hello I was wonders if there is lag when de-initialising the timer  at faster PERIODs <  5ms; in my application I require the faster period, please let me know if this is expected? If said behaviour expected I suppose I can use the counter_en return value to stop my code as needed? Thanks Team.

`from machine import Timer, freq 
print(freq())          # get the current frequency of the CPU
freq(240000000) # set the CPU frequency to 240 MHz
print(freq()) 

count = 0
timeX = Timer(1)

def timer_callback(t):
    print(t)
    global count
    print(count)
    count += 1
    if (count == 50):
        timeX.deinit()

timeX.init(mode=Timer.PERIODIC, period=5, callback=timer_callback)`

**Lag: Count should stop at 49 but goes to 53 when period=5**
![image](https://user-images.githubusercontent.com/20260606/179879186-225de751-aef4-42e9-8baa-776f93e89ce3.png)

**Good: Works great stops at 49 for  period=10**
![image](https://user-images.githubusercontent.com/20260606/179879645-5c913152-e3ec-4e87-bc73-3eacbe25dcd0.png)

**Comment by robert-hh** [comment] 2022-07-20 20:23
The problem is caused by the print statements in the callback. If I drop them, there is no problem, even at 1 ms period and just 160Mhz freq. Code used for the test:
```
from machine import Timer, freq
import time
print(freq()) # get the current frequency of the CPU

count = 0
timex = Timer(1)

def timer_callback(t):
    global count
    count += 1
    if (count == 50):
        t.deinit()

timex.init(mode=Timer.PERIODIC, period=1, callback=timer_callback)
time.sleep_ms(1000)
print("count =", count)
```

**Comment by PrimeTime416** [comment] 2022-07-20 21:24
Kool thanks! I will try it when I get home, for now I ran it on a stimulator and all good with this test code; also is this behavior as per design? and does this behavior depend on other aspects of the callback function? And would `IF (counter_en  == 0):` testing for the Timer `counter_en`  value be a ok approach to guard against said lag? thanks again.

`from machine import Timer 
count = 0
timeX = Timer(1)

def timer_callback(t):
    # print(t)
    global count
    # print(count)
    count += 1
    if (count == 50):
        timeX.deinit()

timeX.init(mode=Timer.PERIODIC, period=1, callback=timer_callback)
while True:
    print(count)`


![image](https://user-images.githubusercontent.com/20260606/180083274-79c404e2-e4a6-4959-a307-bdbfaedf7b09.png)

**Comment by robert-hh** [comment] 2022-07-21 05:18
Just a simple calculation: The print statements send 63 bytes. At 115200 baud and a 10 bit data frame (1 start, 8 data, 1 stop bit), the transfer takes at least 5.5ms.

**Comment by PrimeTime416** [comment] 2022-07-21 16:42
Great thanks got it but somewhat surprised the printing to UART is not on DMA and halting the timer interrupt is not mutually exclusive?

**Comment by robert-hh** [comment] 2022-07-21 16:48
It's not a matter of DMA. Communication just takes it's time, and DMA does not speed up 115200 baud, resulting in 630/115200 seconds = 5.5 ms at least to send the data you have printed.

**Comment by robert-hh** [comment] 2022-07-21 16:57
you could try to increase txbuf of UART to a large value, like 5000. Then, the callback handler can return immediately for longer until the buffer is full.

**Comment by PrimeTime416** [comment] 2022-07-21 19:18
Got it! So if I must use the print then make the string as small as possible, or use global variables as status flags for my ISR, thanks again 🤜🤛.

**Comment by robert-hh** [comment] 2022-07-21 19:31
You're welcome. Please do not forget to close the issue, as it wasn't one.

**Closed** 2022-07-23 13:34 UTC
Labels: port-esp32
